/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypotestRouteImport } from './routes/typotest'
import { Route as LoginRouteImport } from './routes/login'

const TypotestRoute = TypotestRouteImport.update({
  id: '/typotest',
  path: '/typotest',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/typotest': typeof TypotestRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/typotest': typeof TypotestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/typotest': typeof TypotestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/typotest'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/typotest'
  id: '__root__' | '/login' | '/typotest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  TypotestRoute: typeof TypotestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typotest': {
      id: '/typotest'
      path: '/typotest'
      fullPath: '/typotest'
      preLoaderRoute: typeof TypotestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  TypotestRoute: TypotestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
